

proc generate {drv_handle} {
	xdefine_include_file $drv_handle "xparameters.h" "comblock" "NUM_INSTANCES" "DEVICE_ID"  "C_AXIL_BASEADDR" "C_AXIL_HIGHADDR" "C_AXIF_BASEADDR" "C_AXIF_HIGHADDR" "REGS_IN_ENA" "REGS_IN_DWIDTH" "REGS_IN_DEPTH" "REGS_OUT_ENA" "REGS_OUT_DWIDTH" "REGS_OUT_DEPTH" "DRAM_IO_ENA" "DRAM_IO_DWIDTH" "DRAM_IO_AWIDTH" "DRAM_IO_DEPTH" "FIFO_IN_ENA" "FIFO_IN_DWIDTH" "FIFO_IN_DEPTH" "FIFO_IN_AFOFFSET" "FIFO_IN_AEOFFSET" "FIFO_OUT_ENA" "FIFO_OUT_DWIDTH" "FIFO_OUT_DEPTH" "FIFO_OUT_AFOFFSET" "FIFO_OUT_AEOFFSET"
}
