set_property SRC_FILE_INFO {cfile:/home/agustin/Escritorio/Github/QMARL/fpga/QGT_Final/QGT_Final.srcs/constrs_1/new/QGT_debugg.xdc rfile:../../../QGT_Final.srcs/constrs_1/new/QGT_debugg.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/comblock_0_reg5_o[0]} {design_1_i/comblock_0_reg5_o[1]} {design_1_i/comblock_0_reg5_o[2]} {design_1_i/comblock_0_reg5_o[3]}]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/comblock_0_reg1_o[0]} {design_1_i/comblock_0_reg1_o[1]} {design_1_i/comblock_0_reg1_o[2]} {design_1_i/comblock_0_reg1_o[3]}]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/comblock_0_reg3_o[0]} {design_1_i/comblock_0_reg3_o[1]} {design_1_i/comblock_0_reg3_o[2]} {design_1_i/comblock_0_reg3_o[3]}]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/comblock_0_reg4_o[0]} {design_1_i/comblock_0_reg4_o[1]} {design_1_i/comblock_0_reg4_o[2]} {design_1_i/comblock_0_reg4_o[3]}]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/QGT_state_fixpt_0_p11[0]} {design_1_i/QGT_state_fixpt_0_p11[1]} {design_1_i/QGT_state_fixpt_0_p11[2]} {design_1_i/QGT_state_fixpt_0_p11[3]} {design_1_i/QGT_state_fixpt_0_p11[4]} {design_1_i/QGT_state_fixpt_0_p11[5]} {design_1_i/QGT_state_fixpt_0_p11[6]} {design_1_i/QGT_state_fixpt_0_p11[7]} {design_1_i/QGT_state_fixpt_0_p11[8]} {design_1_i/QGT_state_fixpt_0_p11[9]} {design_1_i/QGT_state_fixpt_0_p11[10]} {design_1_i/QGT_state_fixpt_0_p11[11]} {design_1_i/QGT_state_fixpt_0_p11[12]} {design_1_i/QGT_state_fixpt_0_p11[13]} {design_1_i/QGT_state_fixpt_0_p11[14]} {design_1_i/QGT_state_fixpt_0_p11[15]}]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/QGT_state_fixpt_0_p00[0]} {design_1_i/QGT_state_fixpt_0_p00[1]} {design_1_i/QGT_state_fixpt_0_p00[2]} {design_1_i/QGT_state_fixpt_0_p00[3]} {design_1_i/QGT_state_fixpt_0_p00[4]} {design_1_i/QGT_state_fixpt_0_p00[5]} {design_1_i/QGT_state_fixpt_0_p00[6]} {design_1_i/QGT_state_fixpt_0_p00[7]} {design_1_i/QGT_state_fixpt_0_p00[8]} {design_1_i/QGT_state_fixpt_0_p00[9]} {design_1_i/QGT_state_fixpt_0_p00[10]} {design_1_i/QGT_state_fixpt_0_p00[11]} {design_1_i/QGT_state_fixpt_0_p00[12]} {design_1_i/QGT_state_fixpt_0_p00[13]} {design_1_i/QGT_state_fixpt_0_p00[14]} {design_1_i/QGT_state_fixpt_0_p00[15]}]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/QGT_state_fixpt_0_p01[0]} {design_1_i/QGT_state_fixpt_0_p01[1]} {design_1_i/QGT_state_fixpt_0_p01[2]} {design_1_i/QGT_state_fixpt_0_p01[3]} {design_1_i/QGT_state_fixpt_0_p01[4]} {design_1_i/QGT_state_fixpt_0_p01[5]} {design_1_i/QGT_state_fixpt_0_p01[6]} {design_1_i/QGT_state_fixpt_0_p01[7]} {design_1_i/QGT_state_fixpt_0_p01[8]} {design_1_i/QGT_state_fixpt_0_p01[9]} {design_1_i/QGT_state_fixpt_0_p01[10]} {design_1_i/QGT_state_fixpt_0_p01[11]} {design_1_i/QGT_state_fixpt_0_p01[12]} {design_1_i/QGT_state_fixpt_0_p01[13]} {design_1_i/QGT_state_fixpt_0_p01[14]} {design_1_i/QGT_state_fixpt_0_p01[15]}]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/comblock_0_reg2_o[0]} {design_1_i/comblock_0_reg2_o[1]} {design_1_i/comblock_0_reg2_o[2]} {design_1_i/comblock_0_reg2_o[3]}]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/comblock_0_reg0_o[0]} {design_1_i/comblock_0_reg0_o[1]} {design_1_i/comblock_0_reg0_o[2]} {design_1_i/comblock_0_reg0_o[3]}]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/QGT_state_fixpt_0_p10[0]} {design_1_i/QGT_state_fixpt_0_p10[1]} {design_1_i/QGT_state_fixpt_0_p10[2]} {design_1_i/QGT_state_fixpt_0_p10[3]} {design_1_i/QGT_state_fixpt_0_p10[4]} {design_1_i/QGT_state_fixpt_0_p10[5]} {design_1_i/QGT_state_fixpt_0_p10[6]} {design_1_i/QGT_state_fixpt_0_p10[7]} {design_1_i/QGT_state_fixpt_0_p10[8]} {design_1_i/QGT_state_fixpt_0_p10[9]} {design_1_i/QGT_state_fixpt_0_p10[10]} {design_1_i/QGT_state_fixpt_0_p10[11]} {design_1_i/QGT_state_fixpt_0_p10[12]} {design_1_i/QGT_state_fixpt_0_p10[13]} {design_1_i/QGT_state_fixpt_0_p10[14]} {design_1_i/QGT_state_fixpt_0_p10[15]}]]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
