%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.10 and Fixed-Point Designer 7.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [result_re, result_im] = comp_mat_mult_fixpt(a_re, a_im, b_re, b_im)
fm = get_fimath();

result = fi((a_re + fi(1j, 0, 1, 0, fm) * a_im) * (b_re + fi(1j, 0, 1, 0, fm) * b_im), 1, 16, 14, fm);
result_re = fi(real(result), 1, 16, 14, fm);
result_im = fi(imag(result), 1, 16, 14, fm);
end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
