%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.10 and Fixed-Point Designer 7.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [result_re,result_im] = comp_mat_mult_wrapper_fixpt(a_re,a_im,b_re,b_im)
    fm = get_fimath();
    a_re_in = fi( a_re, 1, 16, 14, fm );
    a_im_in = fi( a_im, 1, 16, 14, fm );
    b_re_in = fi( b_re, 1, 16, 14, fm );
    b_im_in = fi( b_im, 1, 16, 14, fm );
    [result_re_out,result_im_out] = comp_mat_mult_fixpt( a_re_in, a_im_in, b_re_in, b_im_in );
    result_re = double( result_re_out );
    result_im = double( result_im_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
